name = "griddles-p1-lean"
version = "0.1.0"
defaultTargets = ["GriddlesP1Lean"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
revision = "8850ed93863d6ce2"

[[lean_lib]]
name = "GriddlesP1Lean"
